server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    # Matrix well-known pour le homeserver
    location /.well-known/matrix/server {
        default_type application/json;
        return 200 '{"m.server": "masolo-synapse.fly.dev:443"}';
        add_header Access-Control-Allow-Origin *;
    }

    # Matrix well-known pour le client
    location /.well-known/matrix/client {
        default_type application/json;
        return 200 '{"m.homeserver": {"base_url": "https://masolo-synapse.fly.dev"}, "m.identity_server": {"base_url": "https://vector.im"}}';
        add_header Access-Control-Allow-Origin *;
    }

    location / {
        try_files  / /index.html;
    }
}
